# Imagem base
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

# Define o diretório de trabalho
WORKDIR /app

# Copia o arquivo csproj e restaura as dependências
COPY *.csproj ./
RUN dotnet restore

# Copia o restante dos arquivos e compila a aplicação
COPY . ./
RUN dotnet publish -c Release -o out

# Cria a imagem final
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .

# Copia o arquivo appsettings.docker.json e renomeia para appsettings.json
COPY appsettings.docker.json appsettings.json

ENTRYPOINT ["dotnet", "entity.dll"]
